name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: "**/package-lock.json"

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Typecheck
        run: npx tsc --noEmit || (echo "Typecheck failed" && exit 1)

      - name: Build
        run: npm run build || (echo "Build failed" && exit 1)

      - name: Deploy to Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npx wrangler pages deploy ./dist --project-name=chillburguergrill --branch=main --commit-dirty=true
